steps:
  - name: Checkout code
    uses: actions/checkout@v2

  - name: Deploy to GitHub Pages
    uses: peaceiris/actions-gh-pages@v3
    with:
      github_token: ${{ secrets.MY_TOKEN }}
      publish_dir: ./docs  # Use ./docs if your files are in a docs folder